# -*- coding: utf-8 -*-
"""gitTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/sergioalbgonz/estructurasDeDatos/blob/master/gitTest.ipynb
"""

def funcion1(name):
  return name
def funcion2(name):
  return name+name
def funcion3(name):
  return name*5
