# -*- coding: utf-8 -*-
"""gitTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnjV08fwktMDKG4AwgwQICerzOE0UNP3
"""

def funcion1(name):
  return name
def funcion2(name):
  return(name+name)
