# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcyMPyezNwfwkNUuu0wmmnY5djQ_VT7m
"""

class TdaTest:
  def __init__(self, primer=0, segundo=0):
    self.primer = primer
    self.segundo = segundo
  
  def __repr__(self):
    return str(self.primer)+","+str(self.segundo)

  def getPrimer(self):
    return self.primer

  def getSegundo(self):
    return self.segundo

  def getSuma(self):
    return self.primer+self.segundo
