# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2jr0sHdUfC2z3RSBESnHWOqkXe4Hc1Q
"""

def test(name):
  return name
